version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: finanzas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: app_finanzas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Cargamos los scripts fijos de SQL para que PostgreSQL los ejecute al inicializar por primera vez.
      # Se ejecutan en orden alfabético por eso se renombran logícamente en destino.
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./backend/insert_categories.sql:/docker-entrypoint-initdb.d/02_insert_categories.sql
      - ./backend/seed_data.sql:/docker-entrypoint-initdb.d/03_seed_data.sql

  backend:
    build:
      context: ./backend
    container_name: finanzas_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: app_finanzas
      DB_PORT: 5432
      PORT: 4000
      JWT_SECRET: super_secreto_docker_123
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: finanzas_frontend
    restart: always
    ports:
      - "5173:80" # Puedes abrir localhost:5173 para ver la app servida por Nginx internamente en el 80
    depends_on:
      - backend

volumes:
  pgdata:
